artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://www.kaggle.com/datasets/sriramr/fruits-fresh-and-rotten-for-classification/Download.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingetion